"""Generate report/numbers.tex — every figure quoted in the report, computed from
the package and committed snapshot so the PDF can never drift from the code.

Usage: python -m scripts.report_numbers
"""

from __future__ import annotations

import math

from perp_spot import backtest, config, data, funding, metrics, stats

OUT = config.ROOT / "report" / "numbers.tex"


def pct(x: float, signed: bool = False) -> str:
    return f"{x * 100:+.1f}\\%" if signed else f"{x * 100:.1f}\\%"


def money(x: float) -> str:
    return f"\\${x:,.0f}"


def sci(x: float) -> str:
    """LaTeX scientific notation, e.g. 3.2e-5 -> \\ensuremath{3.2\\times10^{-5}}."""
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    mant = x / 10**e
    return f"\\ensuremath{{{mant:.1f}\\times10^{{{e}}}}}"


def main() -> None:
    m = data.load_market(config.PRIMARY_SYMBOL)
    d = m.daily
    macros: dict[str, str] = {}

    macros["dataStart"] = str(d["date"].min().date())
    macros["dataEnd"] = str(d["date"].max().date())
    macros["nBars"] = f"{len(d):,}"
    macros["nSymbols"] = str(len(config.SYMBOLS))
    macros["caseStart"] = config.CASE_START
    macros["caseEnd"] = config.CASE_END

    # --- case-study window ---
    books = backtest.run_books(m, config.CASE_START, config.CASE_END)
    for key, res in books.items():
        s = metrics.summarize(res.equity)
        macros[f"{key}Ret"] = pct(s["total_return"], signed=True)
        macros[f"{key}Sharpe"] = f"{s['sharpe']:.2f}"
        macros[f"{key}Sortino"] = f"{s['sortino']:.2f}"
        macros[f"{key}Mdd"] = pct(s["max_drawdown"])
        macros[f"{key}Fund"] = money(res.funding_total)
    macros["breakeven"] = pct(backtest.break_even_funding(m, config.CASE_START, config.CASE_END))

    # --- walk-forward across regimes ---
    wf = backtest.walk_forward(m, freq="QE")
    macros["nQuarters"] = str(wf["window_start"].nunique())
    name = {"carry": "Carry (Δ-neutral)", "perp": "Perp 4x", "spot": "Spot 1x"}
    for key, label in name.items():
        sub = wf[wf["strategy"] == label]
        macros[f"wf{key.capitalize()}Med"] = pct(sub["total_return"].median(), signed=True)
        macros[f"wf{key.capitalize()}Worst"] = pct(sub["total_return"].min(), signed=True)
        macros[f"wf{key.capitalize()}Sharpe"] = f"{sub['sharpe'].median():.2f}"
        macros[f"wf{key.capitalize()}Mdd"] = pct(sub["max_drawdown"].min())
        macros[f"wf{key.capitalize()}Liq"] = str(int(sub["liquidated"].sum()))

    # --- full-history carry ---
    w = funding.holding_window(d, config.HISTORY_START, config.HISTORY_END)
    carry = backtest.strategy.carry_delta_neutral(d, m.funding, w, config.DEFAULT_INVESTMENT)
    cs = metrics.summarize(carry.equity)
    macros["carryFullRet"] = pct(cs["total_return"], signed=True)
    macros["carryFullSharpe"] = f"{cs['sharpe']:.2f}"
    macros["carryFullMdd"] = pct(cs["max_drawdown"])
    macros["carryFullFund"] = money(carry.funding_total)
    macros["fundingAPR"] = pct(funding.funding_apr(m.funding))

    # --- statistics ---
    macros["levelCorr"] = f"{d['spot_close'].corr(d['perp_close']):.6f}"
    macros["returnCorr"] = f"{d['spot_ret'].corr(d['perp_ret']):.6f}"
    macros["basisMean"] = f"{d['basis_bps'].mean():+.2f}"
    macros["basisStd"] = f"{d['basis_bps'].std():.2f}"
    macros["basisHL"] = f"{stats.half_life(d['basis_bps']):.1f}"
    macros["adfP"] = sci(stats.adf(d["basis_bps"]).pvalue)
    macros["cointP"] = f"{stats.engle_granger(d['perp_close'], d['spot_close']).pvalue:.3f}"
    dist = stats.distribution_summary(d["spot_ret"])
    macros["kurtosis"] = f"{dist.excess_kurtosis:.2f}"
    macros["jbP"] = sci(dist.jb_pvalue)
    macros["annVol"] = pct(d["spot_ret"].std() * (config.TRADING_DAYS_PER_YEAR ** 0.5))

    # --- multi-asset walk-forward (median quarterly return + perp liquidations) ---
    rows, liqs = [], []
    for sym in config.SYMBOLS:
        w_ = backtest.walk_forward(data.load_market(sym), freq="QE")
        g = w_.groupby("strategy")["total_return"].median()
        lq = int(w_[w_["strategy"] == "Perp 4x"]["liquidated"].sum())
        rows.append(f"{sym[:3]} & {g['Spot 1x'] * 100:+.1f}\\% & {g['Perp 4x'] * 100:+.1f}\\% "
                    f"& {g['Carry (Δ-neutral)'] * 100:+.1f}\\% & {lq} \\\\")
        liqs.append(lq)
    macros["multiAssetBody"] = "\n".join(rows)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("% Auto-generated by scripts/report_numbers.py — do not edit by hand.\n")
        for k, v in macros.items():
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"Wrote {len(macros)} macros to {OUT}")


if __name__ == "__main__":
    main()
